066 add automatic deploy
yaptide/yaptide pull request #77
Opened 2021-10-09 19:22 UTC by retkiewi

Resolves #66 
Added a deployment job to the CI pipeline

2021-10-09 20:11 UTC, grzanka requested changes

2021-10-09 20:11 UTC, grzanka commented on requirements.txt
> +<<<<<<< HEAD
Fix incorrect merge

2021-10-09 20:11 UTC, grzanka commented on tests/test_main.py
> +<<<<<<< HEAD
Fix incorrect merge

2021-10-09 20:11 UTC, grzanka commented on .github/workflows/test-run.yml
> +            python3 -m pip install --upgrade pip
This should work in venv !

2021-10-09 20:12 UTC, grzanka commented on .github/workflows/test-run.yml
> +            FLASK_ENV=dev FLASK_APP=yaptide.application flask run
What if some `flash run` is already running ?

2021-10-09 20:15 UTC, grzanka commented on .github/workflows/test-run.yml
> +      - uses: appleboy/ssh-action@master
```suggestion
      uses: appleboy/ssh-action@master
```

I suspect this should belong to a step with name above

2021-10-09 20:19 UTC, grzanka commented on .github/workflows/test-run.yml
> +          scp -oProxyJump="ubuntu@149.156.182.181" -i ${{ secrets.DEPLOY_C3_TEST }} -r ..\yaptide ubuntu@30.30.30.8:~
Will it work ?
I am not sure, but how does github action keep secrets?
I suspect they are like strings or environmental variables, not files.
On the other hand `scp` (like `ssh`) expects to see a filename after `-i` option.

To solve this problem you may use an ssh agent, like here:
https://github.com/yaptide/ui/blob/master/.github/workflows/node.js.yml#L47

2021-10-09 20:26 UTC, retkiewi commented on .github/workflows/test-run.yml
> +          scp -oProxyJump="ubuntu@149.156.182.181" -i ${{ secrets.DEPLOY_C3_TEST }} -r ..\yaptide ubuntu@30.30.30.8:~
I suspected this would not work, but wanted to make sure. I was not sure how to solve this securely.

2021-10-09 20:28 UTC, retkiewi commented on .github/workflows/test-run.yml
> +      - uses: appleboy/ssh-action@master
I misunderstood the puprose of the "-", there are a few simmilar errors.

Fixed along with the other errors in b66db34d23825b5daf619e586ef1f6ba1cc16003, also introduced a more consistent step structure.

2021-10-09 20:52 UTC, grzanka commented on .github/workflows/test-run.yml
>        - name: Instal dependencies
```suggestion
      - name: Install dependencies
```

2021-10-09 21:10 UTC, retkiewi commented on .github/workflows/test-run.yml
> +            python3 -m pip install --upgrade pip
Fixed in 7cc44d7adb33d077f0f7719a59d331d0f29abe1d

2021-10-09 21:12 UTC, retkiewi commented on .github/workflows/test-run.yml
> +            FLASK_ENV=dev FLASK_APP=yaptide.application flask run
The command will return an error stating that the port used by flask is already in use.

2021-10-10 07:11 UTC, grzanka commented on .github/workflows/test-run.yml
> +            FLASK_ENV=dev FLASK_APP=yaptide.application flask run
Then we should kill the flask process and run it from scratch

2021-10-10 07:11 UTC, grzanka commented on .github/workflows/test-run.yml
> +            python3 -m venv env
What if venv in `env` directory exists ?

2021-10-10 08:48 UTC, retkiewi commented on .github/workflows/test-run.yml
> +            python3 -m venv env
Since we don't run venv with the --clear option, the venv stays intact if present, but if absent a new venv is created.

2021-10-10 20:25 UTC, grzanka commented on .github/workflows/test-run.yml
> +            python3 -m venv env
ok

2021-10-10 20:31 UTC, grzanka commented on .github/workflows/test-run.yml
> +      - name: Copy files to machine
What about this one which uses rsync instead of scp ?

rsync should accept additional options to copy via intermedia host 
https://github.com/marketplace/actions/ssh-deploy
https://superuser.com/questions/1115715/rsync-files-via-intermediate-host

2021-10-10 20:32 UTC, grzanka commented on .github/workflows/test-run.yml
> +#       - name: Copy files to machine
For debugging consider using this one https://github.com/marketplace/actions/wireguard-ssh

2021-10-10 20:34 UTC, grzanka commented on .github/workflows/test-run.yml
> +# #         if: github.ref == 'refs/heads/master'
If I understand correctly copying the key to the file can be done with this one:
https://github.com/marketplace/actions/install-ssh-key

2021-10-10 20:36 UTC, grzanka commented on .github/workflows/test-run.yml
> +          echo "${{ secrets.DEPLOY_C3_TEST }}" | scp -i /dev/stdin -oProxyJump="ubuntu@149.156.182.181" -r ./* ubuntu@30.30.30.8:~/scptest
Interesting hint from https://github.com/marketplace/actions/install-ssh-key
```SCP is deprecated by OpenSSH due to outdated and inflexible protocol.```
Read more here https://www.openssh.com/txt/release-8.0
```
The scp protocol is outdated, inflexible and not readily fixed. We
recommend the use of more modern protocols like sftp and rsync for
file transfer instead.```

2021-10-14 21:31 UTC, grzanka commented on .github/workflows/test-run.yml
> +      - name: Install ssh key
It is not needed to add ssh key to the file, works well with the agent, as shown here:
https://github.com/yaptide/yaptide/pull/82/files

then only disadvantage of my solution is to disable host checking at proxy server

2021-10-16 09:00 UTC, grzanka commented on .github/workflows/test-run.yml
> +            FLASK_ENV=developement FLASK_APP=yaptide.application nohup flask run >> /dev/null &
Use `screen` instead o f `nohup`.
Straightforward solution described here https://unix.stackexchange.com/questions/266571/remotely-starting-a-screen-session-through-ssh-and-closing-the-ssh-session-immed

Tested on my system:
![image](https://user-images.githubusercontent.com/7374733/137581377-87bbfee3-e476-46ae-8c0c-1c9c863da4e6.png)

To start htop remotely, keep it running and disconnect I type:
```
ssh ubuntu@149.156.182.181 screen -d -m "htop"
```

To check if it is still running, after a while I connect to the machine and then connect to a running `screen` session:
```
ssh ubuntu@149.156.182.181
screen -x
```

Get familiar with `screen` - it is a great tool

2021-10-16 09:58 UTC, retkiewi commented on .github/workflows/test-run.yml
> +            FLASK_ENV=developement FLASK_APP=yaptide.application nohup flask run >> /dev/null &
I've swapped out the ```nohup``` + ```& exit``` for ```screen```.

2021-10-16 10:07 UTC, retkiewi commented on .github/workflows/test-run.yml
> +      - name: Install ssh key
I've swapped the install-ssh action for the ssh-agent action and added the known_hosts file via a script inspired by your solution. 

Regarding the disadvantage, can't we just append the known_hosts file with the output from ssh-keyscan ran from the external machine?
(something like ```ssh <external machine address> 'ssh-keyscan -H <internal machine address>' >> .ssh/known_hosts```)

2021-10-16 10:08 UTC, retkiewi commented on .github/workflows/test-run.yml
> +          echo "${{ secrets.DEPLOY_C3_TEST }}" | scp -i /dev/stdin -oProxyJump="ubuntu@149.156.182.181" -r ./* ubuntu@30.30.30.8:~/scptest
I've removed SCP in favour of rsync.

2021-10-16 11:23 UTC, grzanka approved these changes
Looks OK

2021-10-16 11:23 UTC, merged